name: Publish Angular Library

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # Cache npm packages to speed up future builds
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Install dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libxss1 libasound2 fonts-liberation libappindicator3-1 xdg-utils

      - name: Run tests
        run: npm test

      - name: Set Config NPM Auth
        run: |
          npm config set registry https://registry.npmjs.org
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}

      - name: Build Packages 🔧
        run: npm run build

      - name: Publish package on NPM 📦
        run: npm publish ./dist/material --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
